### ISSUE TITLE
Documentation on setBrightness is incorrect

### ISSUE THREAD

**Issue by apirek** [sparkfun/SparkFun_Alphanumeric_Display_Arduino_Library#15]
### Subject of the issue
The documentation on HT16K33::setBrightness (https://github.com/sparkfun/SparkFun_Alphanumeric_Display_Arduino_Library/blob/a399e8ad069e73813d2d9d30b87397f7f0fa220a/src/SparkFun_Alphanumeric_Display.cpp#L325) and in Example_04_SetBrightness (https://github.com/sparkfun/SparkFun_Alphanumeric_Display_Arduino_Library/blob/a399e8ad069e73813d2d9d30b87397f7f0fa220a/examples/Example_04_SetBrightness/Example_04_SetBrightness.ino#L38) claim that a value 0 turns the display off.

This is incorrect, the value 0 specifies 1/16 duty cycle as per the datasheet, p.12 (https://www.holtek.com/documents/10179/116711/HT16K33v120.pdf).

### Your workbench
* What development board or microcontroller are you using?
* What version of hardware or breakout board are you using? 
* How is the breakout board wired to your microcontroller?
* How is everything being powered?
* Are there any additional details that may help us help you?

### Steps to reproduce
`display.setBrightness(0);`, read datasheet.

### Expected behavior
Documentation matches what the code does.

### Actual behavior
Documentation does not match what the code does.

**Comment by sfe-SparkFro** [comment]
Thanks for the note, should be fixed in v2.2.6!
