### ISSUE TITLE
Unclear Licensing

### ISSUE THREAD

**Issue by zyphlar** [sparkfun/SparkFun_Alphanumeric_Display_Arduino_Library#25]
The library CPP and H files say that the code is "beerware" but LICENSE.md says MIT and CC-SA-4.0.

It's really important to be clear about licensing. Could these files be updated to be clear about what license(s) they're released under?

**Comment by sfe-SparkFro** [comment]
Hi there! Apologies for the unclear and conflicting licenses. All software from SparkFun is meant to use the MIT license (as indicated by LICENSE.md), so I've updated the header comments to match (871796a). Thank you for bringing this to our attention!
