### ISSUE TITLE
Decimal and colon freezes Artemis

### ISSUE THREAD

**Issue by ArrowRaider** [sparkfun/SparkFun_Alphanumeric_Display_Arduino_Library#6]
### Description of the issue
If the colon or decimal point is lit on the Qwiic Alphanumeric Display and the board is a RedBoard Artemis Nano, the board hangs.

### Workbench
* RedBoard Artemis Nano (DEV-15443)
* Qwiic Alphanumeric Display - Red (SPX-16427)
* SparkFun Qwiic Alphanumeric Display Arduino Library - 1.1.2
* Note:  does not hang on SparkFun RedBoard (AVR based)

### Steps to reproduce
Attach Artemis Nano and Display together using Qwiic cable.
Upload the following sketch
```#include <SparkFun_Alphanumeric_Display.h>

HT16K33 display;

void setup() {
  Wire.begin();
  if (!display.begin())
    while (1);
}

void loop() {
  display.print("FOO.");
  digitalWrite(LED_BUILTIN, HIGH);
  delay(500);
  display.print("BAR");
  digitalWrite(LED_BUILTIN, LOW);
  delay(500);
}
```
You can also replace the decimal with a colon and the same behavior will happen.  It will also happen if you use the Colon() or Decimal() functions.  If you send simply, "FOO", it will work correctly but without lighting the segments of course.

### Expected behavior
It should alternate between `FOO.` and `BAR` and the LED should blink.

### Actual behavior
It says `FOO.` and stops

This issue may need to be filed at https://github.com/sparkfun/Arduino_Apollo3/, I am not sure.

**Comment by pmakin-png** [comment]
Hi there @ArrowRaider. Working on replicating this issue now. Need a bit of time. Thanks.

**Comment by pmakin-png** [comment]
Hey there @ArrowRaider. I've committed some changes to master. Will you please clone the current library repo or download the zip and let me know if the issues still persist. If everything checks out, I'll release a new version of the library and get the Arduino library manager up to date.

**Comment by ArrowRaider** [comment]
It is fixed, thanks!
Also, I recently learned of the F() macro and I can confirm that additionally works: `display.print(F("FOO."))`

Thanks for fixing the library metadata too.
